version: '3.8'

services:
  todo-webapp:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - ./assets:/app/assets
      - ./help:/app/help
      - ./img:/app/img
      - ./data:/app/data
      - ./index.html:/app/index.html
      - /tmp/tododata:/tmp/tododata
      - todoconfig:/root/.config/todotxt-git
    restart: unless-stopped

volumes:
  todoconfig:
